import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <main
        style={{
          display: 'flex',
          height: '100vh',
          width: '100vw'
        }}
        className={inter.className}
      >
        {children}
      </main>
    </>
  )
}
